---   
<img align="left" width="110"   src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"> 

<h1 align="center">Tools and Techniques for Data Science</h1>
<h1 align="center">Course: Python for Data Scientist</h1>

---

<h3><div align="right">Muhammad Sheraz(Data Scientist)</div></h3>    

<h1 align="center">Lecture 3.11 (Pandas-03)</h1>

<a href="https://colab.research.google.com/github/arifpucit/data-science/blob/master/Section-3-Python-for-Data-Scientists/Lec-3.11(Pandas-03-Overview-of-Pandas-Dataframe).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="right" width="400" height="400"  src="images/pandas-apps.png"  >

## _Overview of Pandas Dataframe Data Structure_

#### Read about Pandas Data Structures: https://pandas.pydata.org/docs/user_guide/dsintro.html#dsintro

## Learning agenda of this notebook
1. Anatomy of a Dataframe
2. Creating Dataframe
    - An empty dataframe
    - Two-Dimensional NumPy Array
    - Dictionary of Python Lists
    - Dictionary of Panda Series
2. Attributes of a Dataframe
3. Bonus

In [1]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install pandas

In [2]:
import pandas as pd
pd.__version__ , pd.__path__

('1.5.3', ['C:\\Users\\LENOVO\\anaconda3\\lib\\site-packages\\pandas'])

<img align="right" width="500" height="500"  src="images/pandas00.png"  >

## 1. Creating a Dataframe
<br><br>
>**A Pandas Dataframe is a two-dimensional labeled data structure (like SQL table) with heterogeneously typed columns, having both a row and a column index.**

<br><br><br><br>

**```pd.DataFrame(data=None, index=None, columns=None, dtype=None)```**
- Where,
   - `data`: It can be a 2-D NumPy Array, a Dictionary of Python Lists, or a Dictionary of Panda Series (You can also create a dataframe from a file in CSV, Excel, JSON, HTML format or may be from a database table as well).
   - `index`: These are the row indices. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `columns`: These are the column indices or labels. Will default to RangeIndex (0, 1, 2, ..., n), if index argument is not passed and no indexing information is part of input data.
   - `dtype`: Data type to force. Only a single dtype is allowed. If None, infer.

### a. Creating an Empty Dataframe

In [3]:
import pandas as pd
import numpy as np
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


### b. Creating a Dataframe from a 2-D NumPy Array

In [4]:
arr = np.random.randint(10,100, size= (6,5))
print("Numpy Array:\n",arr)

df = pd.DataFrame(data=arr)
print("Pandas Dataframe:\n",df)

Numpy Array:
 [[35 36 53 83 87]
 [10 24 88 71 79]
 [22 50 74 23 17]
 [21 55 20 48 23]
 [73 56 13 52 84]
 [38 35 27 43 41]]
Pandas Dataframe:
     0   1   2   3   4
0  35  36  53  83  87
1  10  24  88  71  79
2  22  50  74  23  17
3  21  55  20  48  23
4  73  56  13  52  84
5  38  35  27  43  41


- Note that both the row indices and the column labels/indices are implicitly set to numerical values from 0 to n-1, since neither of the two is provided while creating the dataframe object. They are also not considered as part of data in the dataframe.
- In majority of the cases the row label is left as default, i.e., 0,1,2,3.... However, the column labels are changed from 0,1,2,3,... to some meaningful values.

In [7]:
# Let us name the column labels of our choice, while creating it
col_labels=['Col1', 'Col2', 'Col3', 'Col4', 'Col5']
df = pd.DataFrame(data=arr, columns=col_labels)
dd = pd.DataFrame(data=arr, columns=df.columns)
df = pd.DataFrame(data=arr, columns=df.columns)
df

Col1  Col2  Col3  Col4  Col5
0    35    36    53    83    87
1    10    24    88    71    79
2    22    50    74    23    17
3    21    55    20    48    23
4    73    56    13    52    84
5    38    35    27    43    41

In [6]:
dd

Col1  Col2  Col3  Col4  Col5
0    35    36    53    83    87
1    10    24    88    71    79
2    22    50    74    23    17
3    21    55    20    48    23
4    73    56    13    52    84
5    38    35    27    43    41

In [23]:
# Let us name the row labels of our choice, while creating it
df = pd.DataFrame(data=arr, index=['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5'])
df

0   1   2   3   4
Row0  60  97  37  70  55
Row1  69  96  91  71  80
Row2  84  33  46  67  17
Row3  66  89  62  63  80
Row4  48  17  29  11  50
Row5  46  97  85  92  55

In [26]:
# Let us name the both row labels and column labels to strings of our choice, while creating it
row_labels = ['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5']
col_labels = ['Col0', 'Col1', 'Col2', 'Col3', 'Col4']
df = pd.DataFrame(data=arr, index=row_labels, columns=col_labels)
df

Col0  Col1  Col2  Col3  Col4
Row0    60    97    37    70    55
Row1    69    96    91    71    80
Row2    84    33    46    67    17
Row3    66    89    62    63    80
Row4    48    17    29    11    50
Row5    46    97    85    92    55

In [27]:
df['Row0']

KeyError: 'Row0'

- You can do this later as well, i.e., after the dataframe has been created with default indices.
- This is done by assigning a list of labels/values to `index` and `columns` attributes of a dataframe object.

In [28]:
arr = np.random.randint(10,100, size= (6,5))
df = pd.DataFrame(data=arr)
df

0   1   2   3   4
0  31  98  46  46  92
1  42  31  28  47  29
2  73  38  26  10  57
3  50  24  59  32  66
4  52  50  56  91  30
5  75  25  73  92  91

In [29]:
row_labels = ['Row0', 'Row1', 'Row2', 'Row3', 'Row4', 'Row5']
col_labels = ['Col0', 'Col1', 'Col2', 'Col3', 'Col4']

df.columns = col_labels
df.index = row_labels
df

Col0  Col1  Col2  Col3  Col4
Row0    31    98    46    46    92
Row1    42    31    28    47    29
Row2    73    38    26    10    57
Row3    50    24    59    32    66
Row4    52    50    56    91    30
Row5    75    25    73    92    91

### c. Creating a Dataframe from a Dictionary of Python Lists
- You can create a dataframe object from a dictionary of Python Lists 
    - The dictionary `Keys` become the column names, and 
    - The dictionary `Values` are lists/arrays containing data for the respective columns.

In [30]:
people = {
    "name" : ["Rauf", "Arif", "Maaz", "Hadeed", "Mujahid", "Mohid"],
    "age" : [52, 51, 26, 22, 18, 17],
    "address": ["Lahore", "Karachi", "Lahore", "Islamabad", "Kakul", "Karachi"],
    "cell" : ["321-123", "320-431", "321-478", "324-446", "321-967", "320-678"],
    "bg": ["B+", "A-", "B+", "O-", "A-", "B+"]
}
people

{'name': ['Rauf', 'Arif', 'Maaz', 'Hadeed', 'Mujahid', 'Mohid'],
 'age': [52, 51, 26, 22, 18, 17],
 'address': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Kakul', 'Karachi'],
 'cell': ['321-123', '320-431', '321-478', '324-446', '321-967', '320-678'],
 'bg': ['B+', 'A-', 'B+', 'O-', 'A-', 'B+']}

In [31]:
# Pass this Dictionary of Python Lists to pd.Dataframe()
df_people = pd.DataFrame(data=people)
df_people

name  age    address     cell  bg
0     Rauf   52     Lahore  321-123  B+
1     Arif   51    Karachi  320-431  A-
2     Maaz   26     Lahore  321-478  B+
3   Hadeed   22  Islamabad  324-446  O-
4  Mujahid   18      Kakul  321-967  A-
5    Mohid   17    Karachi  320-678  B+

- Note that column labels are set as per the keys inside the dictionary object, while the row labels/indices are set to default numerical values.
- You can set the row indices while creating the dataframe by passing the index argument to `pd.DataFrame()` method, or can do that later by assigning the new values to the `index` and `columns` attributes of a dataframe object.

In [32]:
# Let us change the row labels of above dataframe
row_labels = ['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06']
df_people.index = row_labels
df_people

name  age    address     cell  bg
MS01     Rauf   52     Lahore  321-123  B+
MS02     Arif   51    Karachi  320-431  A-
MS03     Maaz   26     Lahore  321-478  B+
MS04   Hadeed   22  Islamabad  324-446  O-
MS05  Mujahid   18      Kakul  321-967  A-
MS06    Mohid   17    Karachi  320-678  B+

### d. Creating a Dataframe from Dictionary of Panda Series
One can think of a dataframe as a dictionary of Panda Series: 
- `Keys` are column names, and 
- `Values` are Series object for the respective columns.

In [33]:
dict = {
    "name": pd.Series(['Arif', 'Hadeed', 'Mujahid']),
    "age": pd.Series([50, 22, 18]),
    "addr": pd.Series(['Lahore', 'Islamabad','Karachi']),
}
df = pd.DataFrame(data=dict)
df

name  age       addr
0     Arif   50     Lahore
1   Hadeed   22  Islamabad
2  Mujahid   18    Karachi

>Note from the above output, that every series object becomes the data of the appropriate column. Moreover, the keys of the dictionary become the column labels.

In [34]:
dict = {
    "name": pd.Series(data=['Arif', 'Hadeed', 'Mujahid', 'Maaz'], index=['a','b','c', 'd']),
    "age": pd.Series(data=[50, 22,np.nan, 18], index=['a','b','c','d']),
    "addr": pd.Series(data=['Lahore', '', 'Peshawer','Karachi'], index=['a','b','c', 'd']),
}
df = pd.DataFrame(dict)
df

name   age      addr
a     Arif  50.0    Lahore
b   Hadeed  22.0          
c  Mujahid   NaN  Peshawer
d     Maaz  18.0   Karachi

>- In the above code and its output, note that every series object has four data values and four corresponding indices.
>- Also note that in the `age` series, we have a NaN value, and in the `addr` series we have an empty string.
>- Another point to note that the row indices of the three series exactly match, in number as well as in sequence/value.
>- A question arise, what if the indices of series are different. See the following code to understand this concept.

In [35]:
import pandas as pd
import numpy as np

In [36]:
dict = {
    "name": pd.Series(['Arif', 'Hadeed', 'Mujahid', 'Maaz'], index=['a','b','c', 'd']),
    "age": pd.Series([50, 22,np.nan, 18], index=['a','x','y','d']),
    "addr": pd.Series(['Lahore', '','Karachi'], index=['a', 'd', 'x']),
}
df = pd.DataFrame(dict)
df

name   age     addr
a     Arif  50.0   Lahore
b   Hadeed   NaN      NaN
c  Mujahid   NaN      NaN
d     Maaz  18.0         
x      NaN  22.0  Karachi
y      NaN   NaN      NaN

In [37]:
df.head(-4)

name   age    addr
a    Arif  50.0  Lahore
b  Hadeed   NaN     NaN

In [38]:
df.tail(-4)

name   age     addr
x  NaN  22.0  Karachi
y  NaN   NaN      NaN

>- In the above code and its output, note that first series object has four data values and four corresponding indices. Similarly, second series object has four data values (with one `np.nan` value) and four corresponding indices, which are a bit different from the first series object. Third series has three data values (with one empty string) and three indices.
>- Note the resulting Dataframe has six rows and three columns.
    - For index 'a' we have value in all the three series objects or columns.
    - For index 'b' we have a value in first series object, and NaN for the second and third column, since the second and third series object has no value corresponding to row index 'b.

## 3. Attributes of Pandas Dataframe
- Like Series, we can access properties/attributes of a dataframe by using dot `.` notation

In [39]:
people = {
    "name" : ["Rauf", "Arif", "Maaz", "Hadeed", "Mujahid", "Mohid"],
    "age" : [52, 51, 26, 22, 18, 17],
    "address": ["Lahore", "Karachi", "Lahore", "Islamabad", "Kakul", "Karachi"],
    "cell" : ["321-123", "320-431", "321-478", "324-446", "321-967", "320-678"],
    "bg": ["B+", "A-", "B+", "O-", "A-", "B+"]
}

df_people = pd.DataFrame(data=people, index=['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'])
df_people

name  age    address     cell  bg
MS01     Rauf   52     Lahore  321-123  B+
MS02     Arif   51    Karachi  320-431  A-
MS03     Maaz   26     Lahore  321-478  B+
MS04   Hadeed   22  Islamabad  324-446  O-
MS05  Mujahid   18      Kakul  321-967  A-
MS06    Mohid   17    Karachi  320-678  B+

In [40]:
# `shape` attribute of a dataframe object return a two value tuple containing rows and columns
# Note the rows count does not include the column labels and column count does not include the row index
df_people.shape 

(6, 5)

In [41]:
# `ndim` attribute of a dataframe object returns number of dimensions (which is always 2)
df_people.ndim

2

In [42]:
# `size` attribute of a dataframe object returns the number of elements in the underlying data
df_people.size

30

In [43]:
# `index` attribute of a dataframe object return the list of row indices and its datatype
df_people.index

Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'], dtype='object')

In [44]:
# `columns` attribute of a dataframe object return the list of column labels and its datatype
df_people.columns

Index(['name', 'age', 'address', 'cell', 'bg'], dtype='object')

In [45]:
#This attribute is used to fetch both index and column names.
df_people.axes

[Index(['MS01', 'MS02', 'MS03', 'MS04', 'MS05', 'MS06'], dtype='object'),
 Index(['name', 'age', 'address', 'cell', 'bg'], dtype='object')]

In [46]:
# `values` attribute of a dataframe object returns a NumPy 2-D having all the values in the DataFrame, 
# without the row indices and column labels
df_people.values

array([['Rauf', 52, 'Lahore', '321-123', 'B+'],
       ['Arif', 51, 'Karachi', '320-431', 'A-'],
       ['Maaz', 26, 'Lahore', '321-478', 'B+'],
       ['Hadeed', 22, 'Islamabad', '324-446', 'O-'],
       ['Mujahid', 18, 'Kakul', '321-967', 'A-'],
       ['Mohid', 17, 'Karachi', '320-678', 'B+']], dtype=object)

In [47]:
df.empty

False

In [48]:
# `dtypes` attribute of a dataframe object return the data type of each column in the dataframe
df_people.dtypes

name       object
age         int64
address    object
cell       object
bg         object
dtype: object

In [49]:
# To check number on non-NA values
df_people.count()

name       6
age        6
address    6
cell       6
bg         6
dtype: int64

# Bonus

#### The `df.info()` Method

In [50]:
#This method prints information about a DataFrame including the row indices, column labels, 
# non-null values count in each column, datatype and memory usage
df_people.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, MS01 to MS06
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     6 non-null      object
 1   age      6 non-null      int64 
 2   address  6 non-null      object
 3   cell     6 non-null      object
 4   bg       6 non-null      object
dtypes: int64(1), object(4)
memory usage: 288.0+ bytes
