---   
<img align="left" width="110"   src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"> 

<h1 align="center">Tools and Techniques for Data Science</h1>
<h1 align="center">Course: Python for Data Scientist</h1>

---

<h3><div align="right">Muhammad Sheraz(Data Scientist)</div></h3>    

<h1 align="center">Lecture 3 (NumPy-03)</h1>

# _Basic Operations on NumPy Arrays.ipynb_

<img align="center" width="500" height="500"  src="images/basicopsonnumpy.png" > 

# Learning agenda of this notebook
- Operations on numPy arrays are done element-wise. This means that you don't explicitly have to write for-loops in order to do these operations!
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.


<img align="left" width="450" height="400"  src="images/ufuncunary.png" > 
<img align="right" width="485" height="500"  src="images/ufuncbinary.png" > 

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

1. Scalar Math
    - On 1-D Arrays
    - On 2-D Arrays
2. Arithmetic operations
    - On 1-D Arrays
    - On 2-D Arrays
3. More Mathematical Operations
    - On 1-D Arrays
    - On 2-D Arrays
4. Aggregate Functions
    - On 1-D Arrays
    - On 2-D Arrays
5. Comparing NumPy Arrays
    - On 1-D Arrays
    - On 2-D Arrays
6. Bonus: Searching 1-D and 2-D NumPy Arrays using `numpy.where()`

In [ ]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install numpy

In [1]:
import numpy as np
np.__version__ , np.__path__

('1.26.3',
 ['C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python310\\site-packages\\numpy'])

## 1. Scalar Math

### a. Scalar Math on 1-D Arrays

In [3]:
import numpy as np
# Create a 1-D array having 4 random integers from 1 to 9
arr = np.random.randint(1,10, size=4)
print("arr: ", arr)

# After the operation a new `ndarray` is returned
print("np.add(arr,2): ",      arr + 2)            # np.add(arr, 2))
print("np.subtract(arr,2): ", arr - 2)            # np.subtract(arr, 2))
print("np.multiply(arr,2): ", arr * 2)            # np.multiply(arr, 2))
print("np.divide(arr,2): ",   arr / 2)            # np.divide(arr, 2))
print("np.mod(arr,2): ",      arr % 2)            # np.mod(arr, 2))

arr3 = arr + 9
print(id(arr), id(arr3))

arr:  [1 8 4 2]
np.add(arr,2):  [ 3 10  6  4]
np.subtract(arr,2):  [-1  6  2  0]
np.multiply(arr,2):  [ 2 16  8  4]
np.divide(arr,2):  [0.5 4.  2.  1. ]
np.mod(arr,2):  [1 0 0 0]
2338401446544 2338405069616


### b. Scalar Math on 2-D Arrays

In [ ]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("Original matrix:\n", matrix)

# After the operation a new `ndarray` is returned
print("np.add(matrix,2): \n",      matrix + 2)            # np.add(matrix, 2))
print("np.subtract(matrix,2): \n", matrix - 2)            # np.subtract(matrix, 2))
print("np.multiply(matrix,2): \n", matrix * 2)            # np.multiply(matrix, 2))
print("np.divide(matrix,2): \n",   matrix / 2)            # np.divide(matrix, 2))
print("np.mod(matrix,2): \n",      matrix % 2)            # np.mod(matrix, 2))

## 2. Arithmetic Operations

### a. Arithmetic Operations on 1-D Arrays

In [1]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)

# After the operation a new `ndarray` is returned
print("np.add(arr1, arr2) = ",      arr1 + arr2)     # np.add(arr1, arr2)
print("np.subtract(arr1, arr2) = ", arr1 - arr2)     # np.subtract(arr1, arr2)
print("np.multiply(arr1, arr2) = ", arr1 * arr2)     # np.multiply(arr1, arr2)
print("np.divide(arr1, arr2) = ",   arr1  / arr2)    # np.divide(arr1, arr2)
print("np.mod(arr1, arr2) = ",      arr1  % arr2)    # np.mod(arr1, arr2) # np.remainder(arr1, arr2)

arr1:  [8 9 8 4]
arr2:  [2 7 5 4]
np.add(arr1, arr2) =  [10 16 13  8]
np.subtract(arr1, arr2) =  [6 2 3 0]
np.multiply(arr1, arr2) =  [16 63 40 16]
np.divide(arr1, arr2) =  [4.         1.28571429 1.6        1.        ]
np.mod(arr1, arr2) =  [0 2 3 0]


### b. Arithmetic Operations on 2-D Arrays

In [4]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)

# After the operation a new `ndarray` is returned
print("np.add(matrix1 , matrix2) = \n",      matrix1 + matrix2) # np.add(matrix1 , matrix2)
print("np.subtract(matrix1 , matrix2) = \n", matrix1 - matrix2) # np.subtract(matrix1 , matrix2)
print("np.multiply(matrix1 , matrix2) = \n", matrix1 * matrix2) # np.multiply(matrix1 , matrix2)
print("np.divide(matrix1 , matrix2) = \n",   matrix1 / matrix2) # np.divide(matrix1 , matrix2)
print("np.mod(matrix1 , matrix2) = \n",      matrix1 % matrix2) # np.remainder(matrix1 , matrix2)

matrix1: 
 [[6 7]
 [2 8]]
matrix2: 
 [[7 6]
 [2 8]]
np.add(matrix1 , matrix2) = 
 [[13 13]
 [ 4 16]]
np.subtract(matrix1 , matrix2) = 
 [[-1  1]
 [ 0  0]]
np.multiply(matrix1 , matrix2) = 
 [[42 42]
 [ 4 64]]
np.divide(matrix1 , matrix2) = 
 [[0.85714286 1.16666667]
 [1.         1.        ]]
np.mod(matrix1 , matrix2) = 
 [[6 1]
 [0 0]]


## 3. More Mathematical Operations

### a. Mathematical Operations on 1-D Array

In [5]:
# Creating 1-D array of 5 elements of random floats between 1 and 10
arr = np.random.rand(5)*10
print("Original ndarray: ", arr)


# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.abs(arr) = ", np.abs(arr))
print("np.square(arr) = ", np.square(arr))
print("np.sqrt(arr) = ", np.sqrt(arr))
print("np.cbrt(arr) = ", np.cbrt(arr))
print("np.log(arr) = ", np.log(arr))
print("np.log2(arr) = ", np.log2(arr))
print("np.log10(arr) = ", np.log10(arr))
print("np.isnan(arr) = ", np.isnan(arr))
print("np.ceil(arr) = ", np.ceil(arr))
print("np.floor(arr) = ", np.floor(arr))
print("np.cumsum(arr) = ", np.cumsum(arr))

Original ndarray:  [3.08192501 4.22047024 3.24168732 7.91711606 5.24829468]
np.abs(arr) =  [3.08192501 4.22047024 3.24168732 7.91711606 5.24829468]
np.square(arr) =  [ 9.49826176 17.81236908 10.50853669 62.68072677 27.54459707]
np.sqrt(arr) =  [1.75554123 2.05437831 1.80046864 2.81373703 2.29091569]
np.cbrt(arr) =  [1.45526032 1.61604561 1.47998407 1.99306901 1.73782512]
np.log(arr) =  [1.1255544  1.43994655 1.17609397 2.06902701 1.6579032 ]
np.log2(arr) =  [1.62383176 2.07740375 1.69674494 2.984975   2.39184873]
np.log10(arr) =  [0.48882207 0.62536084 0.51077112 0.89856701 0.72001821]
np.isnan(arr) =  [False False False False False]
np.ceil(arr) =  [4. 5. 4. 8. 6.]
np.floor(arr) =  [3. 4. 3. 7. 5.]
np.cumsum(arr) =  [ 3.08192501  7.30239525 10.54408257 18.46119864 23.70949332]


### b. Mathematical Operations on 2-D Array

In [ ]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("matrix: \n", matrix)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.square(matrix) = \n", np.square(matrix))
print("np.sqrt(matrix) = \n", np.sqrt(matrix))
print("np.log2(matrix) = \n", np.log2(matrix))
print("np.isnan(matrix) = \n", np.isnan(matrix))
print("np.ceil(matrix) = \n", np.ceil(matrix))
print("np.floor(matrix) = \n", np.floor(matrix))
print("np.cumsum(matrix) = \n", np.cumsum(matrix))

## 4. Aggregate Functions

### a. Aggregate Functions on 1-D Arrays

In [6]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=(5,5))
print("arr: ", arr)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.min(arr) = ",     np.min(arr,axis=0))
print("np.max(arr) = ",     np.max(arr))
print("np.sum(arr) = ",     np.sum(arr))
print("np.prod(arr) = ", np.prod(arr))

arr:  [[6 3 9 3 3]
 [6 5 4 8 6]
 [2 5 2 5 6]
 [8 5 6 9 9]
 [1 2 1 1 3]]
np.min(arr) =  [1 2 1 1 3]
np.max(arr) =  9
np.sum(arr) =  118
np.prod(arr) =  -683999232


In [ ]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

#Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
print("np.mean(arr) = ",    np.mean(arr))

# The np.average() function computes the weighted average, by multiplying of each array element by its weight
# The np.average() is same as np.mean(), when weight is not specified
print("np.average(arr) = ", np.average(arr))

# Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by 
# adding the product of the corresponding elements and dividing the sum by the sum of weights.
#             Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)

arr1 = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print("\narr1: ", arr1)
print("wts:  ", wts)
print("np.average(arr1, weights=wts) = ", np.average(arr1, weights= wts))



In [8]:
# Create a 1-D array having 10 random integers from 1 to 99
arr = np.random.randint(1, 100, size=10)
print("arr: ", arr)

# Median is the value separating the higher half of a data sample from the lower half.
print("np.median(arr) = ",  np.median(arr))

# Percentile is the value below which a given percentage of observations in a group of observations fall.
# 50th percentile is the score at or below which 50% of the scores in the distribution may be found.
print("np.percentile(arr,50) = ",     np.percentile(arr,50))
print("np.percentile(arr,0) = ",     np.percentile(arr,0))
print("np.percentile(arr,100) = ",     np.percentile(arr,100))

# The variance measures the average degree to which each point differs from the mean
# Variance is calculated as the average of squared deviations from mean, i.e., mean((x - x.mean())**2).
print("np.var(arr) = ",    np.var(arr))


# Standard deviation checks how spread out a group of numbers is from the mean
# It is the square root of variance: sqrt(mean((x - x.mean())**2))
print("np.std(arr) = ",    np.std(arr))


arr:  [97 23 49 44 67 64  2 74 68 45]
np.median(arr) =  56.5
np.percentile(arr,50) =  56.5
np.percentile(arr,0) =  2.0
np.percentile(arr,100) =  97.0
np.var(arr) =  658.0100000000001
np.std(arr) =  25.651705596314645


### b. Aggregate Functions on 2-D Arrays

In [9]:
import numpy as np
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

print("np.sum(matrix, axis=0) = ",     np.sum(matrix, axis=0))
print("np.sum(matrix, axis=1) = ",     np.sum(matrix, axis=1))


matrix: 
 [[1 6 9]
 [6 6 9]
 [9 3 8]]
np.sum(matrix, axis=0) =  [16 15 26]
np.sum(matrix, axis=1) =  [16 21 20]


In [ ]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

print("np.min(matrix, axis=0) = ",     np.min(matrix, axis=0))
print("np.min(matrix, axis=1) = ",     np.min(matrix, axis=1))

In [ ]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)


print("np.mean(matrix, axis=0) = ",     np.mean(matrix, axis=0))
print("np.mean(matrix, axis=1) = ",     np.mean(matrix, axis=1))

In [ ]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

# Median is the value separating the higher half of a data sample from the lower half.
print("np.median(matrix, axis=0) = ",     np.median(matrix, axis=0))
print("np.median(matrix, axis=1) = ",     np.median(matrix, axis=1))

Please do practice calculating the percentile, variance and standard deviation along different axis of a 2-D array

## 5. Comparing NumPy Arrays

### a. Comparing NumPy 1-D Arrays
- Returns a Boolean numpy array containing True/False after doing element wise comparison

In [15]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)
print("np.equal(arr1, arr2) = ",      np.where(arr1 == arr2))      # np.equal(arr1, arr2)
print("np.not_equal(arr1, arr2) = ",  arr1 != arr2)      # np.not_equal(arr1, arr2)

print("np.greater(arr1, arr2) = ",      np.where(arr1 > arr2))     # np.greater(arr1, arr2)
print("np.greater_equal(arr1, arr2) = ",  arr1 >= arr2)  # np.greater_equal(arr1, arr2)

print("np.less(arr1, arr2) = ",      arr1 < arr2)        # np.less(arr1, arr2)
print("np.less_equal(arr1, arr2) = ",  arr1 <= arr2)     # np.less_equal(arr1, arr2)

arr1:  [8 5 6 2]
arr2:  [2 5 9 8]
np.equal(arr1, arr2) =  (array([1], dtype=int64),)
np.not_equal(arr1, arr2) =  [ True False  True  True]
np.greater(arr1, arr2) =  (array([0], dtype=int64),)
np.greater_equal(arr1, arr2) =  [ True  True False False]
np.less(arr1, arr2) =  [False False  True  True]
np.less_equal(arr1, arr2) =  [False  True  True  True]


### b. Comparing NumPy 2-D Arrays

In [18]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)



print("np.equal(matrix1, matrix2) = \n",       np.where( matrix1 == matrix2))     
print("np.not_equal(matrix1, matrix2) = \n",    matrix1 != matrix2)     

print("np.greater(matrix1, matrix2) = \n",      matrix1 > matrix2)    
print("np.greater_equal(matrix1, matrix2) = \n",matrix1 >= matrix2) 

print("np.less(matrix1, matrix2) = \n",         matrix1 < matrix2)       
print("np.less_equal(matrix1, matrix2) = \n",   matrix1 <= matrix2)     

matrix1: 
 [[9 1]
 [5 7]]
matrix2: 
 [[3 2]
 [2 7]]
np.equal(matrix1, matrix2) = 
 (array([1], dtype=int64), array([1], dtype=int64))
np.not_equal(matrix1, matrix2) = 
 [[ True  True]
 [ True False]]
np.greater(matrix1, matrix2) = 
 [[ True False]
 [ True False]]
np.greater_equal(matrix1, matrix2) = 
 [[ True False]
 [ True  True]]
np.less(matrix1, matrix2) = 
 [[False  True]
 [False False]]
np.less_equal(matrix1, matrix2) = 
 [[False  True]
 [False  True]]


## 6. Searching NumPy Arrays using `numpy.where()`

### a. Searching NumPy 1-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4, 9, 2, 3, 8])
t1 = np.where(arr == 4)
print(t1)

(array([3, 5, 6], dtype=int64),)


Note: The result is a tuple of 1-D arrays having a single tuple containing the index

In [3]:
import numpy as np
arr = np.array([1, 0, 3, 9, 5, 2, 0, 8])
t1 = np.where(arr == 0)
print(t1)

(array([1, 6]),)


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0)
print(t1)

(array([1, 3, 5, 7], dtype=int64),)


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0, True, False)
print(t1)

[False  True False  True False  True False  True]


Note: The result is a simple 1-D array, when you use the x and y arguments to `np.where()`

### b. Searching NumPy 2-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [6]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 4], [4, 9, 2], [3, 8, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 4)
print(t1)

matrix: 
 [[1 2 3]
 [4 5 4]
 [4 9 2]
 [3 8 6]]
(array([1, 1, 2]), array([0, 2, 0]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices `(1,0)`, `(1,2)` and `(2,0)`

In [7]:
import numpy as np
matrix = np.array([[1, 2, 0], [4, 5, 0], [4, 9, 2], [3, 0, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 0)
print(t1)

matrix: 
 [[1 2 0]
 [4 5 0]
 [4 9 2]
 [3 0 6]]
(array([0, 1, 3]), array([2, 2, 1]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices:
`(0,2)`, `(1,2)` and `(3,1)`

In [8]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
(array([0, 2]), array([1, 0]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for two elements at indices:
`(0,2)` and `(1,0)`

In [9]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0, True, False)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
[[False  True False]
 [False False False]
 [ True False False]
 [False False False]]


**Note:** The result is a simple 2-D array, when you use the `x` and `y` arguments to `np.where()`

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [4, 5, 4, 2], [8, 4, 9, 2], [4, 3, 8, 6]])
t1 = np.where(arr == 4)
print(t1)

(array([0, 1, 1, 2, 3]), array([3, 0, 2, 1, 0]))
