---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Course: Tools and Techniques for Data Science</h1>

---
<h3><div align="right">Instructor: Muhammad Arif Butt, Ph.D.</div></h3>    

<h1 align="center">Lecture 3.4 (NumPy-04)</h1>

<a href="https://colab.research.google.com/github/arifpucit/data-science/blob/master/Section-3-Python-for-Data-Scientists/Lec-3.04(NumPy-04-Array-Indexing-and-Slicing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# _Array Indexing, Subsetting and Slicing.ipynb_

<img align="center" width="500" height="500"  src="images/indexingandslicing.png" > 

# Learning agenda of this notebook
Indexing and Slicing are two of the most common operations that you need to be familiar with when working with Numpy arrays. You will use them when you would like to work with a subset of the array.
1. Indexing NumPy Arrays
    - Indexing 1-D NumPy Arrays
    - Indexing 2-D NumPy Arrays
    - Indexing 3-D NumPy Arrays
2. Slicing NumPy Arrays
    - Slicing 1-D NumPy Arrays
    - Slicing 2-D NumPy Arrays
3. Boolean Array Indexing
    - Boolean Indexing on 1-D NumPy Arrays
    - Boolean Indexing on 2-D NumPy Arrays

In [ ]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install numpy

In [1]:
import numpy as np
np.__version__ , np.__path__

('1.26.3',
 ['C:\\Users\\LENOVO\\AppData\\Roaming\\Python\\Python310\\site-packages\\numpy'])

## 1. Indexing Numpy Arrays
- You can access entire dimension or an individual element of NumPy arrays using indexing.
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 and so on.
- You can use negative indixes as well, which starts. from the last element.

### a. Indexing 1-D NumPy Arrays
- Along a single axis, integers are used to select single elements, and so-called slices are used to select ranges and sequences of elements. 
- Positive integers are used to index elements from the beginning of the array (index starts at 0), and negative integers are used to index elements from the end of the array, where the last element is indexed with –1, the second to last element with –2, and so on.

In [2]:
import numpy as np
mylist = [4, 5, 6, 7, 0, 2, 3]
arr = np.array(mylist, dtype=np.uint8)


print("Original Array \n", arr, "\nArray Shape: ",arr.shape)

# You can access specific elements using positive as well as negative index
print("\narr[0] = ", arr[0])
print("arr[6] = ", arr[6])
print("arr[-1] = ", arr[-1])       
print("arr[-7] = ", arr[-7])  


print("arr[7] = ", arr[7])       # IndexError
print("arr[-8] = ", arr[-8])      # IndexError

Original Array 
 [4 5 6 7 0 2 3] 
Array Shape:  (7,)

arr[0] =  4
arr[6] =  3
arr[-1] =  3
arr[-7] =  4


IndexError: index 7 is out of bounds for axis 0 with size 7

### b. Indexing 2-D NumPy Arrays

In [3]:
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("Original Array \n", arr, "\nArray Shape: ",arr.shape)
print("Strides: ", arr.strides)

# You can access specific elements
print("arr[3][2] = ", arr[3][2])
print("arr[3,2] = ", arr[3,2])

# You can access entire rows
print("arr[3] = ", arr[3])

# Negative indexing
print("arr[-1][-2] = ", arr[-1][-2])    
print("arr[-1, -2] = ", arr[-1, -2]) 
print("arr[-3][-3] = ", arr[-3][-3])    
print("arr[-3, -3] = ", arr[-3, -3])    
print("arr[-3] = ", arr[-3])       
print("arr[-1] = ", arr[-1])       


Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Shape:  (5, 4)
Strides:  (16, 4)
arr[3][2] =  4
arr[3,2] =  4
arr[3] =  [7 3 4 9]
arr[-1][-2] =  3
arr[-1, -2] =  3
arr[-3][-3] =  2
arr[-3, -3] =  2
arr[-3] =  [3 2 4 1]
arr[-1] =  [4 0 3 1]


### c. Indexing 3-D NumPy Arrays

In [4]:
import numpy as np
mylist = [
          [[1, 2, 3], [5, 6, 7], [9, 0, 5]],
          [[8, 1, 6], [1, 9, 4], [5, 8, 2]],
         ]
arr = np.array(mylist)
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)
print("Strides:", arr.strides)


Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)
Strides: (36, 12, 4)


In [5]:
# You can access 2-D matrix at first level
print("\narr[0]: \n", arr[0])
# You can access 2-D matrix at second level
print("arr[1]: \n", arr[1])


arr[0]: 
 [[1 2 3]
 [5 6 7]
 [9 0 5]]
arr[1]: 
 [[8 1 6]
 [1 9 4]
 [5 8 2]]


In [6]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# You can access a specific row at a specific level
print("\narr[0][1]: ", arr[0][1])
print("\narr[0, 1]: ", arr[0, 1])
print("arr[1][2]: ", arr[1][2])
print("arr[1, 2]: ", arr[1, 2])

Original Array:
 [[[1 2 3]
  [5 6 7]
  [9 0 5]]

 [[8 1 6]
  [1 9 4]
  [5 8 2]]]
Array Shape =  (2, 3, 3)

arr[0][1]:  [5 6 7]

arr[0, 1]:  [5 6 7]
arr[1][2]:  [5 8 2]
arr[1, 2]:  [5 8 2]


In [ ]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# You can access a specific element
print("\narr[0][1][2]: ", arr[0][1][2])
print("arr[1][2][1]: ", arr[1][2][1])


In [ ]:
print("Original Array:\n", arr)
print("Array Shape = ",arr.shape)

# Negative indexing
print("\narr[-1][-2][-1]: ", arr[-1][-2][-1])    
print("arr[-2][2]: ", arr[-2][2])    

## 2. Slicing NumPy Arrays
- You can slice a numpy array in a similar fashion as we have sliced Python Lists, with two differences:
    - The difference is that NumPy arrays can be sliced in more than one dimension.
    - The other difference is that, when we slice a Python list we get a completely new list, while in case of numPy arrays, you get a **view** of the original array, which is just a way of accessing array data. Thus the original array is not copied in memory.
- An array can be sliced using `:` symbol, which returns the range of elements specified by the index numbers.
- There are three arguments for slicing arrays, all are optional:
```
array[[start]:[stop][:step]]
```

    - start: specifies from where the slicing should start, inclusive (default is 0) 
    - stop: specifies where it has to stop, exclusive (default is end of the array) 
    - step:  is by-default 1
    
Note: Subarrays that are extracted from arrays using slice operations are alternative views of the same underlying array data. This means that they are arrays that refer to the same data in memory as the original array, but with a different strides configuration.

### a. Slicing 1-D Arrays

In [27]:
import numpy as np
mylist = [4, 5, 6, 7, 0, 2, 3]
arr = np.array(mylist, dtype=np.uint8)
print("Original Array \n", arr, "\nArray Shape = ",arr.shape)

Original Array 
 [4 5 6 7 0 2 3] 
Array Shape =  (7,)


In [28]:
print("\narr[:] = ", arr[:])
print("arr[3:] = ", arr[3:])
print("arr[:4] = ", arr[:4])
print("arr[2:5] = ", arr[2:5])

print("arr[:-2] = ", arr[:-2])
print("arr[-1:] = ", arr[-1:])
print("arr[-1:-4] = ", arr[-1:-4])
print("arr[-1:-4:-1] = ", arr[-1:-4:-1])

# reverse the array using step value as -1
print("arr[::-1] = ", arr[::-1])
print("\nAfter all this arr is same: ", arr)


arr[:] =  [4 5 6 7 0 2 3]
arr[3:] =  [7 0 2 3]
arr[:4] =  [4 5 6 7]
arr[2:5] =  [6 7 0]
arr[:-2] =  [4 5 6 7 0]
arr[-1:] =  [3]
arr[-1:-4] =  []
arr[-1:-4:-1] =  [3 2 0]
arr[::-1] =  [3 2 0 7 6 5 4]

After all this arr is same:  [4 5 6 7 0 2 3]


**Proof of Concept:** Slice of a Python List Returns a New List

In [9]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
# A new list object is created after slicing
list2 = list1[2:5]
list2

[3, 4, 5]

In [11]:
#If we make change to this list, it do not effect the original list
list2[0] = 99

In [12]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
list2

[99, 4, 5]

**Proof of Concept:** Slice of a numPy array returns a **view** of original numPy array

In [14]:
list1 = [1, 2, 3, 4, 5, 6, 7,8, 9]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# A view of the original numPy array is created after slicing
arr2 = arr1[2:5]
arr2

array([3, 4, 5])

In [16]:
# If we make change to this view, it will ofcourse effect the original array
arr2[0] = 99

In [17]:
arr1

array([ 1,  2, 99,  4,  5,  6,  7,  8,  9])

In [18]:
arr2, arr2.strides

(array([99,  4,  5]), (4,))

### b. Slicing 2-D Arrays
- Slicing a two-dimensional array is very similar to slicing a one-dimensional array. You just use a comma to separate the row slice and the column slice.
- Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [19]:
import numpy as np
mylist = [
          [1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [3, 2, 4, 1], 
          [7, 3, 4, 9], 
          [4, 0, 3, 1]
          ]
arr = np.array(mylist)
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Note we have two slice objects (row slice and column slice) in case of 2-D slicing separated by a comma
print("\narr[:,:] = \n", arr[:,:])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[:,:] = 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]]


In [20]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Get the row at index 2
print("arr[2] = ", arr[2])      # you can ignore the : symbol for the column part
print("arr[2,:]= ", arr[2,:])   # for better readability give comma separated two values

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)
arr[2] =  [3 2 4 1]
arr[2,:]=  [3 2 4 1]


In [22]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Get the column at index 1 (Get all the row values of column at index 1)
print("arr[:, 1] = ", arr[:, 1])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)
arr[:, 1] =  [2 6 2 3 0]


In [ ]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

In [17]:
# From the row at index 1, slice elements from index 1 to index 2
print("\narr[1, 1:3] = ",arr[1, 1:3])


arr[1, 1:3] =  [6 7]


In [1]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reversing elements of all rows is tricky. 
# Read it as "select all the rows, and in each row reverse all the column values
print("\narr[:, ::-1] =\n", arr[:, ::-1])

NameError: name 'arr' is not defined

In [23]:
print("Original Array \n", arr, "\nArray Size = ",arr.shape)

# Reverse elements of all columns is also tricky. Actually you want to reverse the elements of all the rows
# Read it as "select all the columns, and in each column reverse all the row values
print("\narr[::-1, :] =\n", arr[::-1, :])

Original Array 
 [[1 2 3 4]
 [5 6 7 8]
 [3 2 4 1]
 [7 3 4 9]
 [4 0 3 1]] 
Array Size =  (5, 4)

arr[::-1, :] =
 [[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]


>- **Slicing 3-D arrays can be performed in the same fashion. The only difference is that we have three comma separated slice objects instead of two and it is a bit tricky to visualize :)**

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [3, 2, 4, 1], [7, 3, 4, 9], [4, 0, 3, 1] ])
print(arr[3,2])
print(arr[3])
print(arr[-1, -2]) 
print(arr[-3][-3])    
print(arr[-3])       
print(arr[2, 1:3])
print(arr[::-1, :])
print(arr[2::2, 0::2])

4
[7 3 4 9]
3
2
[3 2 4 1]
[2 4]
[[4 0 3 1]
 [7 3 4 9]
 [3 2 4 1]
 [5 6 7 8]
 [1 2 3 4]]
[[3 4]
 [4 3]]


## 3. Boolean/Fancy Array Indexing

- NumPy provides another convenient method to index arrays, called fancy indexing. With fancy indexing, an array can be indexed with another NumPy array, a Python list, or a sequence of integers, whose values select elements in the indexed array. Fancy indexing requires that the elements in the array or list used for indexing are integers.

- Boolean indexing is an extremely intuitive and elegant way of selecting contents from a numPy array based on logical conditions.
- In simple words, we can slice NumPy arrays by either:
    - Provide a condition inside the `[]` operator
    - Provide a Boolean mask corresponding to indexes in the array.
- If the value at an index of that list is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

>- **Note:** Unlike normal slicing which creates a view, Boolean/Fancy Indexing creates a copy of numPy array.

>- **Note:** The Python keywords `and` and `or` do not work with boolean arrays. Use `&` and `|` instead

### a. Boolean/Fancy Indexing on 1-D Arrays

In [23]:
# Fancy Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)
print(arr[np.array([0, 2, 4, 9])])
print(arr[[0, 2, 4, 9]])

Original Array:  [80 37 81 77 17 98 53 94 79 88]
[80 81 17 88]
[80 81 17 88]


In [24]:
# Boolean Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)
print(arr > 50)
print(arr[arr>50])

Original Array:  [61  4 94 13 26 70 21 79 65 33]
[ True False  True False False  True False  True  True False]
[61 94 70 79 65]


In [25]:
# Boolean Indexing
import numpy as np
# creating 1-D array of size 10 of int type b/w interval (1,100) 
arr = np.random.randint(1, 101, 10)
print("Original Array: ", arr)

# Getting even values from array
print("\narr[arr%2 == 0] = ",arr[arr%2==0])
# Getting odd values from array
print("arr[arr%2 == 1] = ",[arr%2==1])

# Getting values greater than 50
print("\narr[arr > 50] = ",arr[arr > 50])
# Getting values between 25 and 75 both exclusive
print("arr[arr>30 & arr<60] = ",arr[(arr>30) & (arr<60)])

Original Array:  [ 7 77 85 58 20 84 69 23 16 86]

arr[arr%2 == 0] =  [58 20 84 16 86]
arr[arr%2 == 1] =  [array([ True,  True,  True, False, False, False,  True,  True, False,
       False])]

arr[arr > 50] =  [77 85 58 84 69 86]
arr[arr>30 & arr<60] =  [58]


In [26]:
# We can use a mask instead of mentioning a condition as done above
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("Original Array: ", arr1)

mask=[False, False, False, True, False]
arr2 = arr1[mask]

print("Filtered Array: ", arr2)  

Original Array:  [1 2 3 4 5]
Filtered Array:  [4]


### b. Boolean/Fancy Indexing on 2-D Arrays

**Example 1:**

In [27]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[3 4 1 5 6]
 [7 7 5 5 8]
 [4 8 8 9 1]
 [9 9 5 1 8]
 [1 6 7 3 8]] 
Matrix Shape =  (5, 5)


>Suppose we want a new matrix from above matrix, that only contains rows at index 0, 2, and 3

In [28]:
# Create a corresponding boolean mask
rows_wanted = np.array( [True, False, True, True, False] )

matrix2 = matrix1[rows_wanted, :]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[3 4 1 5 6]
 [4 8 8 9 1]
 [9 9 5 1 8]] 
Matrix Shape =  (3, 5)


**Example 2:**

In [29]:
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[6 3 7 5 9]
 [8 4 1 9 7]
 [8 4 5 1 2]
 [9 9 8 8 3]
 [9 1 1 1 2]] 
Matrix Shape =  (5, 5)


>Suppose we want a new matrix from above matrix, that only contains columns at index 1 and 3 only

In [30]:
# Create a corresponding boolean mask
cols_wanted = np.array( [False, True, False, True, False] )

matrix2 = matrix1[ : , cols_wanted]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[3 5]
 [4 9]
 [4 1]
 [9 8]
 [1 1]] 
Matrix Shape =  (5, 2)


**Example 3:**

In [32]:
import numpy as np
# By passing a tuple to size means rows and columns
matrix1 = np.random.randint(low = 1, high = 10, size = (5,5))
print("Original matrix \n", matrix1, "\nMatrix Shape = ",matrix1.shape)

Original matrix 
 [[9 3 6 6 3]
 [2 5 3 9 9]
 [8 3 2 2 9]
 [1 3 5 7 6]
 [6 7 5 7 8]] 
Matrix Shape =  (5, 5)


>Suppose we want a new matrix from above 5x5 matrix, that contains inner 3x3 matrix

In [33]:
rows_wanted = np.array( [False, True, True, True, False] )

matrix2 = matrix1[ rows_wanted , :]
print("\nFiltered matrix \n", matrix2, "\nMatrix Shape = ",matrix2.shape)


Filtered matrix 
 [[2 5 3 9 9]
 [8 3 2 2 9]
 [1 3 5 7 6]] 
Matrix Shape =  (3, 5)


In [34]:
cols_wanted = np.array( [False, True, True, True, False] )

matrix3 = matrix2[ :, cols_wanted]
print("\nFiltered matrix \n", matrix3, "\nMatrix Shape = ",matrix3.shape)


Filtered matrix 
 [[5 3 9]
 [3 2 2]
 [3 5 7]] 
Matrix Shape =  (3, 3)


**Can you think of doing this in one step or in a more elegant fashion?**

In [38]:
print(matrix1)
matrix3 = matrix1[1:4, 1:4]
print("\nFiltered matrix \n", matrix3, "\nMatrix Shape = ",matrix3.shape)

[[9 3 6 6 3]
 [2 5 3 9 9]
 [8 3 2 2 9]
 [1 3 5 7 6]
 [6 7 5 7 8]]

Filtered matrix 
 [[5 3 9]
 [3 2 2]
 [3 5 7]] 
Matrix Shape =  (3, 3)


In [36]:
matrix2 = matrix1[ 1 : -1,  1 : -1 ]
matrix2

array([[5, 3, 9],
       [3, 2, 2],
       [3, 5, 7]])

# Four Slicing Problems with Solutions

<img align="center" width="500" height="500"  src="images/slicingQ.jpeg" > 

In [40]:
m1 = np.array([
            [0,1,2,3,4,5],
            [6,7,8,9,10,11],
            [12,13,14,15,16,17],
            [18,19,20,21,22,23],
            [24,25,26,27,28,29],
            [30,31,32,33,34,35]
])

In [41]:
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
m1[0,3:5]

array([3, 4])

In [43]:
m1[4:, 4:]

array([[28, 29],
       [34, 35]])

In [44]:
m2 = m1[:,2]

In [45]:
m2.strides

(24,)

In [46]:
m1[2::2, 0::2]

array([[12, 14, 16],
       [24, 26, 28]])